# This file contains the configuration for mkdocs

# Site settings
site_name: GIRAF Wiki
site_author: '@aau-giraf'
repo_name: 'aau-giraf/wiki'
repo_url: 'https://github.com/aau-giraf/wiki'

extra_css: 
  - 'extra/extra.css'

sidebar: true

# Theme settings
theme:
  name: 'material'
  font: 
    text: 'Open Sans'
    code: 'Roboto Mono'
  palette:
    primary: 'blue-grey'
    accent: 'indigo'
  logo: 'extra/giraf.png'
  feature:
      tabs: true

# Plugins
plugins:
    - search
    - awesome-pages

    
# Markdown extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: true
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.emoji
