name: Publish docs via GitHub Pages 2.0
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Deploy docs 2.0
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v1

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@1.25
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
